const $=id=>document.getElementById(id),n=id=>Math.max(0,Number($(id)?.value)||0),rp=x=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(x||0);
const holidays={'2026-01-01':'Tahun Baru Masehi','2026-01-16':'Isra Mikraj Nabi Muhammad SAW','2026-02-17':'Tahun Baru Imlek 2577 Kongzili','2026-03-19':'Hari Suci Nyepi','2026-03-21':'Idulfitri 1447 H','2026-03-22':'Idulfitri 1447 H','2026-04-03':'Wafat Yesus Kristus','2026-04-05':'Kebangkitan Yesus Kristus','2026-05-01':'Hari Buruh Internasional','2026-05-14':'Kenaikan Yesus Kristus','2026-05-27':'Iduladha 1447 H','2026-05-31':'Hari Raya Waisak 2570 BE','2026-06-01':'Hari Lahir Pancasila','2026-06-16':'Tahun Baru Islam 1448 H','2026-08-17':'Proklamasi Kemerdekaan RI','2026-08-25':'Maulid Nabi Muhammad SAW','2026-12-25':'Kelahiran Yesus Kristus'};
let calDate=new Date();const f=(l,id,step='1')=>`<label><span>${l}</span><input id="${id}" type="number" inputmode="decimal" step="${step}" min="0" value="0"></label>`;
function monthCalendar(){return `<div class="calendarBox"><div class="calHead"><button type="button" onclick="changeMonth(-1)">‹</button><b id="monthTitle"></b><button type="button" onclick="changeMonth(1)">›</button></div><div class="weekHead"><b>Min</b><b>Sen</b><b>Sel</b><b>Rab</b><b>Kam</b><b>Jum</b><b>Sab</b></div><div id="calendar" class="calendarGrid"></div><div class="legend"><span>🔴 Libur nasional</span><span>🟢 Masuk</span><span>🟣 Libur nasional + masuk</span></div><small class="muted">Tekan tanggal yang benar-benar kamu masuk. Tekan lagi untuk membatalkan.</small></div>`}
function app(){$('app').innerHTML=`<header><strong>GajiKu</strong><small>Simulasi gaji & lembur · GRATIS</small></header><main><h2>Simulasi Gaji</h2><div class="card">${f('Gaji pokok','b')}${f('Tunjangan tetap','a')}${f('Tunjangan variabel','v')}<label><span>Jenis perhitungan</span><select id="workHours" onchange="updateWorkMode()"><option value="8">8 JAM</option><option value="12">12 JAM / SHIFT</option><option value="bap">BAP</option></select></label><div id="modeNote" class="note"></div>${monthCalendar()}<label><span>Tanggal lembur tambahan (opsional)</span><input id="otdate" type="date" onchange="updateDateInfo()"></label>${f('Jam lembur tambahan','h','0.5')}${f('Potongan lain-lain','p')}</div><div class="result"><small>Hari masuk bulan ini</small><b id="wd">0</b><small>Mode</small><b id="workHoursOut">8 JAM</b><small>Pola dari kalender</small><b id="patternStatus">-</b><small>Lembur wajib / tambahan</small><b id="mandatory">0 / 0 jam</b><small>Total lembur</small><b id="lo">Rp0</b><small>BPJS Kesehatan pekerja (1%)</small><b id="health">Rp0</b><small>JHT pekerja (2%)</small><b id="jht">Rp0</b><small>JP pekerja (1%)</small><b id="jp">Rp0</b><small>Total BPJS pekerja</small><b id="bo">Rp0</b><small>Estimasi gaji bersih</small><b id="o">Rp0</b></div><button class="primary" onclick="calcSim()">Hitung Simulasi</button><div class="legal" id="legal"></div></main><footer>GajiKu · Tahap uji coba gratis</footer>`;calDate=new Date();renderCalendar();$('otdate').value=new Date().toISOString().slice(0,10);updateWorkMode();updateDateInfo()}
function keyDate(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}function getWorkSet(){return new Set(JSON.parse(localStorage.getItem('workdays')||'[]'))}
function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),set=getWorkSet();$('monthTitle').textContent=new Date(y,m).toLocaleDateString('id-ID',{month:'long',year:'numeric'});let html='';for(let i=0;i<first;i++)html+='<div class="day empty"></div>';for(let d=1;d<=last;d++){const key=keyDate(y,m+1,d),red=!!holidays[key],on=set.has(key);html+=`<button type="button" class="day ${red?'holiday':''} ${on?'worked':''}" onclick="toggleWork('${key}')"><span>${d}</span>${red?'<i>LIBUR</i>':''}</button>`}$('calendar').innerHTML=html;syncWork()}
function changeMonth(x){calDate=new Date(calDate.getFullYear(),calDate.getMonth()+x,1);renderCalendar()}function toggleWork(k){const s=getWorkSet();s.has(k)?s.delete(k):s.add(k);localStorage.setItem('workdays',JSON.stringify([...s].sort()));renderCalendar();updateDateInfo()}
function workData(){const arr=[...getWorkSet()].sort(),activeMonth=`${calDate.getFullYear()}-${String(calDate.getMonth()+1).padStart(2,'0')}`,monthDays=arr.filter(x=>x.startsWith(activeMonth));let max=0,run=0,prev=null;for(const x of arr){const d=new Date(x+'T12:00:00');run=prev&&((d-prev)/86400000===1)?run+1:1;max=Math.max(max,run);prev=d}const sat=monthDays.filter(x=>new Date(x+'T12:00:00').getDay()===6).length;return {days:monthDays.length,maxStreak:max,sat,pattern:(sat>=2||max>=6)?'6':'5',monthDays}}
function syncWork(){const w=workData();$('wd').textContent=w.days;$('patternStatus').textContent=w.pattern==='6'?'6 hari / minggu':'5 hari / minggu'}
function updateWorkMode(){const h=$('workHours').value;$('workHoursOut').textContent=h==='bap'?'BAP':h+' JAM';if(h==='12'){$('modeNote').innerHTML='<b>12 JAM / SHIFT:</b> jam kerja terjadwal. Jam ke-9–12 tidak otomatis dianggap lembur.';$('legal').innerHTML='<b>Mode 12 jam:</b> simulasi shift; lembur tambahan dihitung terpisah.'}else if(h==='bap'){$('modeNote').innerHTML='<b>BAP:</b> model baru untuk pengujian slip: 7 jam kerja + 1 jam lembur wajib setiap tanggal masuk. Hari ke-7/libur resmi memakai tarif khusus.';$('legal').innerHTML='<b>Mode BAP:</b> hari kerja biasa: 1 jam wajib = 1,5×. Hari istirahat/libur resmi mengikuti skema 2×/3×/4× sesuai pola 5/6 hari. Gunakan untuk membandingkan dengan slip gaji sebelumnya.'}else{$('modeNote').innerHTML='<b>8 JAM:</b> mode umum 8 jam kerja.';$('legal').innerHTML='<b>Mode 8 jam:</b> lembur tambahan hari kerja mengikuti 1,5× untuk jam pertama dan 2× berikutnya; hari istirahat/libur resmi mengikuti tarif khusus.'}}
function consecutiveRun(k){const set=getWorkSet();let d=new Date(k+'T12:00:00'),run=0;while(set.has(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)){run++;d.setDate(d.getDate()-1)}return run}
function updateDateInfo(){const d=$('otdate').value;if(!d)return;const dt=new Date(d+'T12:00:00'),w=dt.getDay(),red=holidays[d],worked=getWorkSet().has(d),run=consecutiveRun(d),pattern=workData().pattern;let status;if(red&&worked)status=`🟣 Libur nasional + masuk — ${red}`;else if(red)status=`🔴 Libur nasional — ${red}`;else if(worked&&((pattern==='6'&&run>=7)||(pattern==='5'&&run>=6)))status=`🟠 Hari istirahat mingguan — masuk ${run} hari berturut-turut`;else if(worked)status=`🟢 Hari masuk — ${['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'][w]}`;else status='Hari tidak ditandai masuk';$('dateStatus').textContent=status;syncWork()}
function baseData(){const b=n('b'),a=n('a'),v=n('v'),total=b+a+v;return {total,base:(b+a<0.75*total)?0.75*total:b+a}}
function dateTypeFor(d,pattern){const worked=getWorkSet().has(d),run=consecutiveRun(d);if(holidays[d]&&worked)return 'holiday';if(worked&&((pattern==='6'&&run>=7)||(pattern==='5'&&run>=6)))return 'weekly';return 'work'}
function holidayPay(hour,pattern){return hour*(pattern==='5'?17:17)}
function bapMandatory(){const x=baseData(),hour=x.base/173,w=workData(),pattern=w.pattern;let total=0,mandatoryHours=0;for(const s of w.monthDays){const cat=dateTypeFor(s,pattern);mandatoryHours++;if(cat==='work')total+=hour*1.5;else total+=holidayPay(hour,pattern)}return {x,hour,w,pattern,total,mandatoryHours}}
function extraPay(){const x=baseData(),hour=x.base/173,h=n('h'),d=$('otdate').value,pattern=workData().pattern,cat=dateTypeFor(d,pattern);let total=0;for(let i=1;i<=h;i++){let mult=cat==='work'?(i===1?1.5:2):(pattern==='5'?(i<=8?2:i===9?3:4):(i<=7?2:i===8?3:4));total+=hour*mult}return total}
function calcBPJS(base){const health=Math.min(base,12000000)*.01,jp=Math.min(base,10547400)*.01,jht=base*.02;return {health,jht,jp,total:health+jht+jp}}
function calcSim(){const mode=$('workHours').value,x=baseData(),bp=calcBPJS(x.total),other=n('p');let mandatory=0,mandatoryHours=0,totalExtra=0;if(mode==='bap'){const r=bapMandatory();mandatory=r.total;mandatoryHours=r.mandatoryHours;totalExtra=extraPay()}else{totalExtra=extraPay()}const totalOT=mandatory+totalExtra;$('wd').textContent=workData().days;$('mandatory').textContent=mode==='bap'?mandatoryHours+' / '+n('h')+' jam':'0 / '+n('h')+' jam';$('lo').textContent=rp(totalOT);$('health').textContent=rp(bp.health);$('jht').textContent=rp(bp.jht);$('jp').textContent=rp(bp.jp);$('bo').textContent=rp(bp.total);$('o').textContent=rp(x.total+totalOT-bp.total-other)}
app();