const $=id=>document.getElementById(id),n=id=>Math.max(0,Number($(id)?.value)||0),rp=x=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(x||0);const f=(l,id,step='1')=>`<label><span>${l}</span><input id="${id}" type="number" inputmode="decimal" step="${step}" min="0" value="0"></label>`;
const holidays={'2026-01-01':'Tahun Baru Masehi','2026-01-16':'Isra Mikraj Nabi Muhammad SAW','2026-02-17':'Tahun Baru Imlek 2577 Kongzili','2026-03-19':'Hari Suci Nyepi','2026-03-21':'Idulfitri 1447 H','2026-03-22':'Idulfitri 1447 H','2026-04-03':'Wafat Yesus Kristus','2026-04-05':'Kebangkitan Yesus Kristus','2026-05-01':'Hari Buruh Internasional','2026-05-14':'Kenaikan Yesus Kristus','2026-05-27':'Iduladha 1447 H','2026-05-31':'Hari Raya Waisak 2570 BE','2026-06-01':'Hari Lahir Pancasila','2026-06-16':'Tahun Baru Islam 1448 H','2026-08-17':'Proklamasi Kemerdekaan RI','2026-08-25':'Maulid Nabi Muhammad SAW','2026-12-25':'Kelahiran Yesus Kristus'};
const tabs=[['gaji','Gaji'],['lembur','Lembur'],['sim','Simulasi']];let calDate=new Date();
function nav(t){return `<nav>${tabs.map(x=>`<button class="${x[0]==t?'on':''}" onclick="show('${x[0]}')">${x[1]}</button>`).join('')}</nav>`}
function monthCalendar(){return `<div class="calendarBox"><div class="calHead"><button type="button" onclick="changeMonth(-1)">‹</button><b id="monthTitle"></b><button type="button" onclick="changeMonth(1)">›</button></div><div class="weekHead"><b>Min</b><b>Sen</b><b>Sel</b><b>Rab</b><b>Kam</b><b>Jum</b><b>Sab</b></div><div id="calendar" class="calendarGrid"></div><div class="legend"><span>🔴 Libur nasional</span><span>🟢 Tanggal masuk</span></div><small class="muted">Tekan tanggal yang benar-benar kamu masuk. Tekan lagi untuk membatalkan. Sistem membaca pola dari tanggal masuk yang kamu tandai.</small></div>`}
function common(){return `${f('Gaji pokok','b')}${f('Tunjangan tetap','a')}${f('Tunjangan variabel','v')}${monthCalendar()}`}
function show(t='gaji'){let c='';if(t==='gaji')c=`<h2>Kalkulator Gaji</h2><div class="card">${common()}${f('Potongan lain-lain','p')}</div><div class="result"><small>Total upah kotor</small><b id="gross">Rp0</b><small>Gaji bersih</small><b id="o">Rp0</b></div><button class="primary" onclick="calcG()">Hitung</button>`;if(t==='lembur')c=`<h2>Kalkulator Lembur</h2><div class="card">${common()}<label><span>Tanggal lembur</span><input id="otdate" type="date" onchange="updateDateInfo()"></label>${f('Jam lembur','h','0.5')}<div class="note">Tanggal merah otomatis merah. Jika tanggal merah kamu tandai masuk, lembur memakai tarif hari libur. Jika sekaligus hari istirahat mingguan, sistem memakai skema hari istirahat.</div></div><div class="result"><small>Status tanggal</small><b id="dateStatus">-</b><small>Hari masuk bulan ini</small><b id="wd">0</b><small>Pola terdeteksi</small><b id="patternStatus">-</b><small>Dasar upah lembur</small><b id="basis">Rp0</b><small>Upah per jam</small><b id="hourly">Rp0</b><small>Total lembur</small><b id="o">Rp0</b></div><button class="primary" onclick="calcO()">Hitung</button>`;if(t==='sim')c=`<h2>Simulasi Gaji</h2><div class="card">${common()}<label><span>Tanggal lembur</span><input id="otdate" type="date" onchange="updateDateInfo()"></label>${f('Jam lembur','h','0.5')}${f('Potongan lain-lain','p')}</div><div class="result"><small>Hari masuk</small><b id="wd">0</b><small>Pola terdeteksi</small><b id="patternStatus">-</b><small>Status tanggal lembur</small><b id="dateStatus">-</b><small>Dasar upah lembur</small><b id="basis">Rp0</b><small>Upah per jam</small><b id="hourly">Rp0</b><small>Total lembur</small><b id="lo">Rp0</b><small>BPJS Kesehatan pekerja (1%)</small><b id="health">Rp0</b><small>JHT pekerja (2%)</small><b id="jht">Rp0</b><small>JP pekerja (1%, batas upah)</small><b id="jp">Rp0</b><small>Total BPJS pekerja</small><b id="bo">Rp0</b><small>Estimasi gaji bersih</small><b id="o">Rp0</b></div><button class="primary" onclick="calcSim()">Hitung Simulasi</button>`;$('app').innerHTML=`<header><strong>GajiKu</strong><small>Kalkulator gaji & lembur · GRATIS</small></header>${nav(t)}<main>${c}</main><footer>GajiKu · Tahap uji coba gratis</footer>`;calDate=new Date();renderCalendar();const today=new Date().toISOString().slice(0,10);if($('otdate'))$('otdate').value=today;updateDateInfo()}
function keyDate(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function getWorkSet(){return new Set(JSON.parse(localStorage.getItem('workdays')||'[]'))}
function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),set=getWorkSet();if($('monthTitle'))$('monthTitle').textContent=new Date(y,m).toLocaleDateString('id-ID',{month:'long',year:'numeric'});let html='';for(let i=0;i<first;i++)html+='<div class="day empty"></div>';for(let d=1;d<=last;d++){const key=keyDate(y,m+1,d),red=!!holidays[key],on=set.has(key);html+=`<button type="button" class="day ${red?'holiday':''} ${on?'worked':''}" onclick="toggleWork('${key}')"><span>${d}</span>${red?'<i>LIBUR</i>':''}</button>`}if($('calendar'))$('calendar').innerHTML=html;syncWork()}
function changeMonth(x){calDate=new Date(calDate.getFullYear(),calDate.getMonth()+x,1);renderCalendar()}
function toggleWork(k){const s=getWorkSet();s.has(k)?s.delete(k):s.add(k);localStorage.setItem('workdays',JSON.stringify([...s].sort()));renderCalendar();updateDateInfo()}
function workData(){const arr=[...getWorkSet()].sort(),activeMonth=`${calDate.getFullYear()}-${String(calDate.getMonth()+1).padStart(2,'0')}`,monthDays=arr.filter(x=>x.startsWith(activeMonth)),dates=arr.map(x=>new Date(x+'T12:00:00'));let max=0,run=0,prev=null;for(const d of dates){run=prev&&((d-prev)/86400000===1)?run+1:1;max=Math.max(max,run);prev=d}const saturday=monthDays.filter(x=>new Date(x+'T12:00:00').getDay()===6).length;const weeks={};monthDays.forEach(x=>{const d=new Date(x+'T12:00:00'),key=`${d.getFullYear()}-${Math.floor((d-new Date(d.getFullYear(),0,1))/604800000)}`;(weeks[key]??=[]).push(x)});const counts=Object.values(weeks).map(a=>a.length);const avg=counts.length?counts.reduce((a,b)=>a+b,0)/counts.length:0;const pattern=(saturday>=2||avg>=5.5)?'6':'5';return {days:monthDays.length,maxStreak:max,saturday,avg,pattern,arr}}
function syncWork(){const w=workData();if($('wd'))$('wd').textContent=w.days;if($('patternStatus'))$('patternStatus').textContent=w.pattern==='6'?'6 hari / minggu':'5 hari / minggu'}
function consecutiveRun(k){const set=getWorkSet();let d=new Date(k+'T12:00:00'),run=0;while(set.has(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)){run++;d.setDate(d.getDate()-1)}return run}
function updateDateInfo(){const d=$('otdate')?.value;if(!d)return;const dt=new Date(d+'T12:00:00'),w=dt.getDay(),red=holidays[d],worked=getWorkSet().has(d),run=consecutiveRun(d);let status;if(red)status=`🔴 Libur nasional — ${red}${worked?' · 🟢 kamu masuk':''}`;else if(worked&&run>=7)status=`🟠 Hari istirahat mingguan terlewati · masuk ${run} hari berturut-turut`;else if(worked)status=`🟢 Hari masuk — ${['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'][w]}`;else if(w===0||w===6)status='Hari istirahat mingguan';else status='Hari tidak ditandai masuk';document.querySelectorAll('#dateStatus').forEach(x=>x.textContent=status);syncWork()}
function baseData(){const b=n('b'),a=n('a'),v=n('v'),total=b+a+v;return {total,base:(b+a<0.75*total)?0.75*total:b+a}}
function dateType(){const d=$('otdate')?.value;if(!d)return 'work';const worked=getWorkSet().has(d),dt=new Date(d+'T12:00:00'),w=dt.getDay(),run=consecutiveRun(d);if(holidays[d]&&worked)return 'holiday-worked';if(holidays[d])return 'holiday';if(worked&&run>=7)return 'weekly';if(w===0||w===6)return 'weekly';return 'work'}
function detectedPattern(){return workData().pattern}
function multiplier(day,pattern,hour){if(day==='work')return hour===1?1.5:2;if(pattern==='5')return hour<=8?2:hour===9?3:4;return hour<=7?2:hour===8?3:4}
function calcOT(){const x=baseData(),h=n('h'),hour=x.base/173,pattern=detectedPattern(),day=dateType();let total=0,remaining=h,pos=0;while(remaining>0){const whole=Math.floor(pos)+1,step=Math.min(remaining,1);total+=hour*multiplier(day,pattern,whole)*step;remaining-=step;pos+=step}return {x,h,hour,total,day,pattern}}
function calcO(){const r=calcOT();$('basis').textContent=rp(r.x.base);$('hourly').textContent=rp(r.hour);$('o').textContent=rp(r.total);$('wd').textContent=workData().days;$('dateStatus').textContent=r.day==='holiday'||r.day==='holiday-worked'?`🔴 Libur nasional${r.day==='holiday-worked'?' · 🟢 kamu masuk':''} — ${holidays[$('otdate').value]}`:r.day==='weekly'?'Hari istirahat mingguan / pola istirahat':'Hari kerja';$('patternStatus').textContent=r.pattern==='6'?'6 hari / minggu':'5 hari / minggu'}
function calcBPJS(base){const health=Math.min(base,12000000)*.01,jp=Math.min(base,10547400)*.01,jht=base*.02;return {health,jht,jp,total:health+jht+jp}}
function calcG(){const x=baseData(),bp=calcBPJS(x.total),other=n('p'),gross=x.total;out(gross-bp.total-other);if($('gross'))$('gross').textContent=rp(gross)}
function calcSim(){const r=calcOT(),bp=calcBPJS(r.x.total),other=n('p'),w=workData();$('wd').textContent=w.days;$('basis').textContent=rp(r.x.base);$('hourly').textContent=rp(r.hour);$('lo').textContent=rp(r.total);$('health').textContent=rp(bp.health);$('jht').textContent=rp(bp.jht);$('jp').textContent=rp(bp.jp);$('bo').textContent=rp(bp.total);$('patternStatus').textContent=r.pattern==='6'?'6 hari / minggu':'5 hari / minggu';$('dateStatus').textContent=r.day==='holiday'||r.day==='holiday-worked'?`🔴 Libur nasional${r.day==='holiday-worked'?' · 🟢 kamu masuk':''} — ${holidays[$('otdate').value]}`:r.day==='weekly'?'Hari istirahat mingguan / pola istirahat':'Hari kerja';out(r.x.total+r.total-bp.total-other)}function out(x){$('o').textContent=rp(x)}show();